import { assertNoForbiddenOpsKeys } from "@/lib/ops/safety";
import type { OpsDashboardData } from "@/lib/ops/types";

const syncSoapDestination = "https://www.bringhurstdo.com/syncsoap";
const syncSafetyDestination = "https://www.bringhurstdo.com/syncsafety";
const bringhurstDoDestination = "https://www.bringhurstdo.com";

// Metadata-only operator config and **sample mock data** for the private Ops console.
//
// Visual guide (see app/ops/_components/ops-data-status.tsx):
// - Red highlight = mock sample data (metrics, weekly report, project health) — ignore values
// - Amber highlight = static repo config (accounts, brand, targets) — applicable to workflows
// - White/green = live Postgres content, LinkedIn connections, marketing export
//
// Never add PHI, patient identifiers, encounter IDs, transcripts, secret values,
// cookies, tokens, raw logs, or clinical payloads to this module.
export const opsDashboardData: OpsDashboardData = {
  generatedAt: "2026-06-06T09:00:00-04:00",
  boundaries: [
    "Metadata summaries only",
    "No PHI or clinical payloads",
    "No secret values or raw logs",
    "Manual approval before social posting or spend",
  ],
  brandProfiles: [
    {
      id: "kyle-bringhurst",
      displayName: "Kyle Bringhurst",
      role: "Founder voice for practical build notes",
      voiceTone: [
        "Direct, operator-led, and specific",
        "Measured optimism without hype",
        "Founder learning in public without exposing private ops details",
      ],
      allowedTopics: [
        "Founder lessons from building healthcare and compliance software",
        "Manual content operations, product discipline, and small-team execution",
        "Public project updates that have been reviewed for safety and claims",
      ],
      prohibitedClaims: [
        "Do not claim clinical, financial, legal, or safety outcomes without review",
        "Do not imply autonomous posting, ad spending, or business control",
        "Do not share private conversations, contact details, or internal dashboards",
      ],
      requiredDisclaimers: [
        "Manual approval required before posting",
        "No AI, OAuth, posting API, or ad-spend automation is connected",
      ],
      safetyNotes: [
        "Keep personal anecdotes public-safe and non-identifying",
        "Use aggregate business context only",
      ],
      sourceBoundary:
        "Founder content may use public-safe operator notes only; no private messages, credentials, or raw logs.",
    },
    {
      id: "bringhurstdo",
      displayName: "BringhurstDO",
      role: "Parent company and metadata-only ops aggregator",
      voiceTone: [
        "Calm, systems-minded, and operational",
        "Plain language about governance and decision support",
        "Conservative about future integrations and automation",
      ],
      allowedTopics: [
        "Metadata-only ops dashboard principles",
        "Manual reporting, content workflows, and project coordination",
        "Public company updates that avoid private security posture details",
      ],
      prohibitedClaims: [
        "Do not present mock dashboard data as live business intelligence",
        "Do not reveal internal controls, cost details, credentials, or raw logs",
        "Do not imply BringhurstDO controls SyncSOAP clinical workflows",
      ],
      requiredDisclaimers: [
        "BringhurstDO aggregates summaries; source apps retain sensitive data",
        "Manual approval required before publishing or spending",
      ],
      safetyNotes: [
        "Keep public pages separate from private ops routes",
        "Use aggregate metadata only",
      ],
      sourceBoundary:
        "BringhurstDO content may use public site and aggregate ops summaries only; no private route content should be copied into public posts.",
    },
    {
      id: "syncsoap",
      displayName: "SyncSOAP",
      role: "HIPAA-sensitive clinical documentation product",
      voiceTone: [
        "Clinical workflow-aware, careful, and evidence-seeking",
        "Practical for small clinics before enterprise claims",
        "Specific about workflow pain without using clinical examples",
      ],
      allowedTopics: [
        "Documentation workflow burden at an aggregate level",
        "Small-clinic pilot readiness and product positioning",
        "Metadata-only security, compliance evidence status, and manual review posture",
      ],
      prohibitedClaims: [
        "Do not claim diagnosis, treatment, billing, compliance, or outcome guarantees",
        "Do not compare clinical performance without reviewed evidence",
        "Do not use patient stories, encounter details, transcripts, or clinical payloads",
      ],
      requiredDisclaimers: [
        "Marketing context must remain metadata-only",
        "No PHI, patient identifiers, encounter text, transcripts, or clinical payloads",
        "Manual approval required before posting",
      ],
      safetyNotes: [
        "Use general workflow language only",
        "Avoid screenshots or examples from clinical use",
      ],
      sourceBoundary:
        "SyncSOAP content may use product positioning and aggregate readiness notes only; PHI and clinical payloads must stay inside SyncSOAP.",
    },
    {
      id: "syncsafety",
      displayName: "SyncSafety",
      role: "Industrial safety and EHS workflow product",
      voiceTone: [
        "Clear, operational, and practical for safety leaders",
        "Focused on reducing administrative friction",
        "Careful about compliance language and filing implications",
      ],
      allowedTopics: [
        "Safety workflow organization and documentation discipline",
        "EHS leader pain points at a public-safe aggregate level",
        "Manual content operations and public product updates",
      ],
      prohibitedClaims: [
        "Do not imply automatic regulatory filing or legal compliance guarantees",
        "Do not claim incident reduction, cost savings, or audit outcomes without review",
        "Do not store or quote private workplace incidents or employee details",
      ],
      requiredDisclaimers: [
        "Manual approval required before posting or spending",
        "No social, ad, or compliance filing API is connected",
      ],
      safetyNotes: [
        "Use public-safe workplace workflow framing",
        "Keep metrics aggregate and manually entered until integrations are approved",
      ],
      sourceBoundary:
        "SyncSafety content may use public product positioning and aggregate workflow notes only; no private incident narratives or employee details.",
    },
  ],
  audienceProfiles: [
    {
      id: "physicians",
      label: "Clinicians",
      description:
        "Clinical users who care about documentation burden, reviewability, and patient-safety-adjacent workflow clarity.",
      contentUse: [
        "Use concise workflow language",
        "Respect clinical responsibility and avoid replacing judgment",
        "Avoid clinical examples unless separately approved and de-identified outside this app",
      ],
      safetyNotes: [
        "No PHI or encounter details",
        "No diagnostic, treatment, or billing guarantees",
      ],
    },
    {
      id: "clinic owners",
      label: "Small Clinic Owners",
      description:
        "Operators weighing practical adoption, setup burden, trust, and cost discipline.",
      contentUse: [
        "Emphasize narrow pilots, manual review, and operational fit",
        "Keep cost and adoption claims measured",
        "Use aggregate readiness signals only",
      ],
      safetyNotes: [
        "No customer identifiers",
        "No unsupported ROI claims",
      ],
    },
    {
      id: "investors",
      label: "Investors",
      description:
        "Business readers looking for market logic, execution discipline, and product sequencing.",
      contentUse: [
        "Discuss strategy, constraints, and learning loops",
        "Separate mock/local state from live traction",
        "Avoid implying validated metrics before they exist",
      ],
      safetyNotes: [
        "No private financial details",
        "No pipeline names or contact details",
      ],
    },
    {
      id: "general",
      label: "General Founder Audience",
      description:
        "Public readers interested in product building, operations, and transparent progress notes.",
      contentUse: [
        "Keep language clear and low-jargon",
        "Make the useful takeaway practical",
        "Avoid private implementation details",
      ],
      safetyNotes: [
        "No credentials, private messages, raw logs, or identifiers",
        "Manual approval before posting",
      ],
    },
    {
      id: "EHS leaders",
      label: "EHS Leaders",
      description:
        "Safety and operations leaders who care about documentation discipline, compliance workflow clarity, and reducing administrative drag.",
      contentUse: [
        "Use practical workplace workflow language",
        "Separate organization and tracking from legal or regulatory guarantees",
        "Keep incident examples public-safe and non-identifying",
      ],
      safetyNotes: [
        "No employee details or private incident narratives",
        "No legal, safety, or compliance outcome guarantees",
      ],
    },
  ],
  draftReviewChecklist: [
    "Confirm the source update is metadata-only and contains no PHI, credentials, private messages, raw logs, transcripts, or clinical payloads.",
    "Confirm every SyncSOAP draft stays at product, workflow, or aggregate evidence level.",
    "Confirm claims are supportable and do not promise clinical, legal, safety, financial, or compliance outcomes.",
    "Confirm the selected brand voice and audience framing match the publication target.",
    "Confirm every post has the exact generated UTM link and a public destination URL.",
    "Confirm a human manually approves the post before publishing.",
    "Confirm no ad spend, posting, database write, OAuth flow, or external API mutation is triggered.",
  ],
  projects: [
    {
      id: "syncsoap",
      name: "SyncSOAP",
      role: "HIPAA-sensitive clinical app",
      status: "Mock metadata only",
      statusTone: "watch",
      owner: "BringhurstDO",
      environment: "External app, no live connection",
      lastReviewedAt: "2026-06-06",
      metadataBoundary:
        "Only aggregate health, deployment, invite, cost, and evidence summaries belong here.",
      metrics: [
        {
          label: "Site health",
          value: "Mock: healthy",
          detail: "Future source: metadata-only status endpoint",
          tone: "neutral",
        },
        {
          label: "Compliance evidence",
          value: "Mock: collecting",
          detail: "Future source: evidence status summary, not evidence files",
          tone: "watch",
        },
        {
          label: "User / invite counts",
          value: "Mock: pending",
          detail: "Future source: aggregate counts only",
          tone: "neutral",
        },
      ],
      nextActions: [
        "Define a SyncSOAP metadata export contract",
        "Keep HIPAA app data ownership inside SyncSOAP",
        "Review pilot-readiness evidence summary weekly",
      ],
      integrationTodos: [
        "Read-only SyncSOAP health summary",
        "Aggregate AWS cost subtotal",
        "Aggregate AI usage and cost totals",
      ],
    },
    {
      id: "syncsafety",
      name: "SyncSafety",
      role: "Industrial compliance product",
      status: "Mock metadata only",
      statusTone: "neutral",
      owner: "BringhurstDO",
      environment: "Future project metadata feed",
      lastReviewedAt: "2026-06-06",
      metadataBoundary:
        "Only operational status, marketing status, and aggregate business metrics belong here.",
      metrics: [
        {
          label: "Product status",
          value: "Mock: active",
          detail: "Future source: public app uptime summary",
          tone: "good",
        },
        {
          label: "Content calendar",
          value: "Mock: 4 drafts",
          detail: "Draft queue requires manual approval",
          tone: "watch",
        },
        {
          label: "Marketing metrics",
          value: "Mock: not connected",
          detail: "Future source: read-only marketing aggregate",
          tone: "neutral",
        },
      ],
      nextActions: [
        "Create first read-only project status file",
        "Draft LinkedIn launch-support post",
        "Document public metrics worth tracking",
      ],
      integrationTodos: [
        "Read-only deployment status",
        "Read-only marketing aggregate",
        "Content calendar export",
      ],
    },
    {
      id: "bringhurstdo",
      name: "BringhurstDO",
      role: "Parent company and ops aggregator",
      status: "Phase 2 mock workspace",
      statusTone: "good",
      owner: "BringhurstDO",
      environment: "This app, protected by Basic Auth",
      lastReviewedAt: "2026-06-06",
      metadataBoundary:
        "BringhurstDO aggregates summaries; source apps retain their own sensitive data.",
      metrics: [
        {
          label: "Ops console",
          value: "Mock: protected",
          detail: "Basic Auth middleware is temporary",
          tone: "watch",
        },
        {
          label: "Weekly report",
          value: "Mock: expanded",
          detail: "No AI generation connected",
          tone: "good",
        },
        {
          label: "Content queue",
          value: "Mock: working",
          detail: "Manual tracking only; no posting API",
          tone: "good",
        },
      ],
      nextActions: [
        "Replace Basic Auth before mutation features",
        "Review mock operator report every Friday",
        "Keep future integration contracts metadata-only",
      ],
      integrationTodos: [
        "Read-only deployment status",
        "Scheduled local report generation",
        "Future auth provider or SSO",
      ],
    },
  ],
  contentIdeas: [],
  draftPosts: [],
  utmCampaignLinks: [],
  weeklyScorecard: [
    {
      id: "posts",
      label: "Posts",
      value: "5",
      unit: "manual rows",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "good",
      notes: ["Counts draft rows marked posted or ready for manual publishing"],
    },
    {
      id: "followers",
      label: "Followers",
      value: "Manual",
      unit: "weekly total",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "neutral",
      notes: ["Enter aggregate follower totals only"],
    },
    {
      id: "websiteClicks",
      label: "Website Clicks",
      value: "Mock: 14",
      unit: "UTM clicks",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "watch",
      notes: ["Use public page click totals only; no visitor identifiers"],
    },
    {
      id: "leads",
      label: "Leads",
      value: "Manual",
      unit: "aggregate count",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "neutral",
      notes: ["Counts only; no names, emails, or contact details"],
    },
    {
      id: "conversations",
      label: "Conversations",
      value: "Manual",
      unit: "aggregate count",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "neutral",
      notes: ["Track count and source category, not message content"],
    },
    {
      id: "spend",
      label: "Spend",
      value: "$0",
      unit: "manual weekly total",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "good",
      notes: ["No ad-spend mutation is connected"],
    },
    {
      id: "revenue",
      label: "Revenue",
      value: "$0",
      unit: "manual weekly total",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "neutral",
      notes: ["Use aggregate totals only"],
    },
  ],
  manualMetricEntries: [
    {
      id: "metric-posts-2026-06-07",
      projectId: "bringhurstdo",
      metricId: "posts",
      label: "Manual posts prepared",
      value: "5",
      unit: "rows",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      enteredAt: "2026-06-06",
      notes: ["Includes approved, ready, and manually posted draft rows"],
    },
    {
      id: "metric-clicks-2026-06-07",
      projectId: "bringhurstdo",
      metricId: "websiteClicks",
      label: "UTM link clicks",
      value: "14",
      unit: "aggregate clicks",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      enteredAt: "2026-06-06",
      notes: ["Placeholder manual total; no analytics provider connected"],
    },
    {
      id: "metric-spend-2026-06-07",
      projectId: "bringhurstdo",
      metricId: "spend",
      label: "Paid spend",
      value: "0",
      unit: "USD",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      enteredAt: "2026-06-06",
      notes: ["No ad platform mutation or budget control connected"],
    },
  ],
  accountRegistry: [
    {
      id: "account-founder-linkedin",
      projectId: "kyle-bringhurst",
      name: "Kyle Bringhurst LinkedIn",
      kind: "founder",
      platform: "LinkedIn",
      handle: "kyle-bringhurst",
      profileUrl: "https://www.linkedin.com/in/kyle-bringhurst/",
      role: "Founder account",
      notes: ["User-provided registry row; verify public profile URL before posting"],
      accountType: "Founder profile",
      publicHandle: "kyle-bringhurst",
      status: "active",
      statusTone: "good",
      purpose: "Manual founder-led updates after approval.",
      sourceBoundary:
        "Track public profile context and aggregate metrics only; do not store inbox content.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Conversations", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Contact details"],
      integrationPlaceholder: "Future read-only LinkedIn aggregate metrics.",
    },
    {
      id: "account-founder-instagram",
      projectId: "kyle-bringhurst",
      name: "Kyle Bringhurst Instagram",
      kind: "founder",
      platform: "Instagram",
      handle: "@kyle_bringhurst",
      profileUrl: "https://www.instagram.com/kyle_bringhurst",
      role: "Founder account",
      notes: ["Mock registry row; manual posting only"],
      accountType: "Founder profile",
      publicHandle: "@kyle_bringhurst",
      status: "active",
      statusTone: "good",
      purpose: "Optional founder visual updates after approval.",
      sourceBoundary:
        "Track public profile context and aggregate metrics only; no private message content.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Instagram aggregates.",
    },
    {
      id: "account-founder-facebook",
      projectId: "kyle-bringhurst",
      name: "Kyle Bringhurst Facebook",
      kind: "founder",
      platform: "Facebook",
      handle: "Facebook page",
      profileUrl: "https://www.facebook.com/share/19qjmzY6Pt/?mibextid=wwXIfr",
      role: "Founder account",
      notes: [
        "Active manual Facebook page row; no Meta Business integration, OAuth, posting API, or autoposting is connected",
        "Temporary share URL; replace later with the canonical Facebook page URL or username",
      ],
      accountType: "Founder page",
      publicHandle: "Facebook page",
      status: "active",
      statusTone: "good",
      purpose: "Manual founder Facebook updates after approval only.",
      sourceBoundary:
        "Track public profile context and aggregate metrics only; no private message content.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Facebook aggregates.",
    },
    {
      id: "account-founder-x",
      projectId: "kyle-bringhurst",
      name: "Kyle Bringhurst X",
      kind: "founder",
      platform: "X",
      handle: "@kyle_bringhurst",
      profileUrl: "https://x.com/kyle_bringhurst",
      role: "Founder account",
      notes: ["Mock registry row; manual short-form posting only"],
      accountType: "Founder profile",
      publicHandle: "@kyle_bringhurst",
      status: "active",
      statusTone: "good",
      purpose: "Manual short-form updates and UTM-linked threads.",
      sourceBoundary: "Track public aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only X aggregate metrics.",
    },
    {
      id: "account-bringhurstdo-linkedin",
      projectId: "bringhurstdo",
      name: "BringhurstDO LinkedIn",
      kind: "project",
      platform: "LinkedIn",
      handle: "bringhurstdo-llc",
      profileUrl: "https://www.linkedin.com/company/bringhurstdo-llc/",
      role: "Parent company account",
      notes: ["Mock registry row; public company positioning only"],
      accountType: "Company page",
      publicHandle: "bringhurstdo-llc",
      status: "active",
      statusTone: "good",
      purpose: "Parent-company updates and project routing.",
      sourceBoundary: "Track public page context and aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Leads", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Contact details"],
      integrationPlaceholder: "Future read-only LinkedIn aggregate metrics.",
    },
    {
      id: "account-bringhurstdo-instagram",
      projectId: "bringhurstdo",
      name: "BringhurstDO Instagram",
      kind: "project",
      platform: "Instagram",
      handle: "@BringhurstDO_LLC",
      profileUrl: "https://www.instagram.com/BringhurstDO_LLC",
      role: "Parent company account",
      notes: ["Mock registry row; no Meta API is connected"],
      accountType: "Project account",
      publicHandle: "@BringhurstDO_LLC",
      status: "active",
      statusTone: "good",
      purpose: "Optional public visual updates after approval.",
      sourceBoundary: "Track public aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Instagram aggregates.",
    },
    {
      id: "account-bringhurstdo-facebook",
      projectId: "bringhurstdo",
      name: "BringhurstDO Facebook",
      kind: "project",
      platform: "Facebook",
      handle: "Facebook page",
      profileUrl: "https://www.facebook.com/share/1TTzXAuJEq/?mibextid=wwXIfr",
      role: "Parent company account",
      notes: [
        "Active manual Facebook page row; no Meta Business integration, OAuth, posting API, or autoposting is connected",
        "Temporary share URL; replace later with the canonical Facebook page URL or username",
      ],
      accountType: "Project page",
      publicHandle: "Facebook page",
      status: "active",
      statusTone: "good",
      purpose: "Manual public company Facebook updates after approval only.",
      sourceBoundary: "Track public aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Facebook aggregates.",
    },
    {
      id: "account-bringhurstdo-x",
      projectId: "bringhurstdo",
      name: "BringhurstDO X",
      kind: "project",
      platform: "X",
      handle: "@BringhurstDOLLC",
      profileUrl: "https://x.com/BringhurstDOLLC",
      role: "Parent company account",
      notes: ["Mock registry row; no X API is connected"],
      accountType: "Project account",
      publicHandle: "@BringhurstDOLLC",
      status: "active",
      statusTone: "good",
      purpose: "Manual short-form company updates.",
      sourceBoundary: "Track public aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only X aggregate metrics.",
    },
    {
      id: "account-syncsoap-linkedin",
      projectId: "syncsoap",
      name: "SyncSOAP LinkedIn",
      kind: "project",
      platform: "LinkedIn",
      handle: "syncsoap",
      profileUrl: "https://www.linkedin.com/showcase/syncsoap/",
      role: "Project account",
      notes: ["Mock registry row; SyncSOAP content remains metadata-only"],
      accountType: "Project company page",
      publicHandle: "syncsoap",
      status: "active",
      statusTone: "good",
      purpose: "Manual product positioning and pilot-readiness posts.",
      sourceBoundary:
        "Track account presence and aggregate public metrics only; no clinical payloads.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Contact lists"],
      integrationPlaceholder: "Future read-only LinkedIn aggregate metrics.",
    },
    {
      id: "account-syncsoap-instagram",
      projectId: "syncsoap",
      name: "SyncSOAP Instagram",
      kind: "project",
      platform: "Instagram",
      handle: "@sync.soap",
      profileUrl: "https://www.instagram.com/sync.soap",
      role: "Project account",
      notes: ["Mock registry row; no patient stories or clinical examples"],
      accountType: "Project account",
      publicHandle: "@sync.soap",
      status: "active",
      statusTone: "good",
      purpose: "Optional visual workflow-positioning posts.",
      sourceBoundary:
        "Track aggregate public metrics only; SyncSOAP remains metadata-only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Instagram aggregates.",
    },
    {
      id: "account-syncsoap-facebook",
      projectId: "syncsoap",
      name: "SyncSOAP Facebook",
      kind: "project",
      platform: "Facebook",
      handle: "Facebook page",
      profileUrl: "https://www.facebook.com/share/18hs3eYKAo/?mibextid=wwXIfr",
      role: "Project account",
      notes: [
        "Active manual Facebook page row; no Meta Business integration, OAuth, posting API, or autoposting is connected",
        "Temporary share URL; replace later with the canonical Facebook page URL or username",
      ],
      accountType: "Project page",
      publicHandle: "Facebook page",
      status: "active",
      statusTone: "good",
      purpose: "Manual SyncSOAP Facebook updates after approval only.",
      sourceBoundary:
        "Track aggregate public metrics only; no clinical payloads or message bodies.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Facebook aggregates.",
    },
    {
      id: "account-syncsoap-x",
      projectId: "syncsoap",
      name: "SyncSOAP X",
      kind: "project",
      platform: "X",
      handle: "@SyncSOAP",
      profileUrl: "https://x.com/SyncSOAP",
      role: "Project account",
      notes: ["Mock registry row; approved UTM links only"],
      accountType: "Project account",
      publicHandle: "@SyncSOAP",
      status: "active",
      statusTone: "good",
      purpose: "Short workflow-positioning posts with approved UTM links.",
      sourceBoundary:
        "Track public aggregate counts only; no private message content.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only X aggregate metrics.",
    },
    {
      id: "account-syncsafety-linkedin",
      projectId: "syncsafety",
      name: "SyncSafety LinkedIn",
      kind: "project",
      platform: "LinkedIn",
      handle: "syncsafety",
      profileUrl: "https://www.linkedin.com/showcase/syncsafety/",
      role: "Project account",
      notes: ["Mock registry row; manual safety-workflow posts only"],
      accountType: "Project company page",
      publicHandle: "syncsafety",
      status: "active",
      statusTone: "good",
      purpose: "Manual safety-workflow posts and launch notes.",
      sourceBoundary: "Track aggregate public metrics and UTM totals only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Leads", "Website clicks"],
      forbiddenData: ["Credentials", "Lead contact details", "Message bodies"],
      integrationPlaceholder: "Future read-only LinkedIn aggregate metrics.",
    },
    {
      id: "account-syncsafety-instagram",
      projectId: "syncsafety",
      name: "SyncSafety Instagram",
      kind: "project",
      platform: "Instagram",
      handle: "@sync.safety",
      profileUrl: "https://www.instagram.com/sync.safety",
      role: "Project account",
      notes: ["Mock registry row; no Meta API is connected"],
      accountType: "Project account",
      publicHandle: "@sync.safety",
      status: "active",
      statusTone: "good",
      purpose: "Optional visual education channel for safety workflow topics.",
      sourceBoundary: "Track aggregate public metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Instagram aggregates.",
    },
    {
      id: "account-syncsafety-facebook",
      projectId: "syncsafety",
      name: "SyncSafety Facebook",
      kind: "project",
      platform: "Facebook",
      handle: "Facebook page",
      profileUrl: "https://www.facebook.com/share/18okyHRhg5/?mibextid=wwXIfr",
      role: "Project account",
      notes: [
        "Active manual Facebook page row; no Meta Business integration, OAuth, posting API, or autoposting is connected",
        "Temporary share URL; replace later with the canonical Facebook page URL or username",
      ],
      accountType: "Project page",
      publicHandle: "Facebook page",
      status: "active",
      statusTone: "good",
      purpose: "Manual SyncSafety Facebook updates after approval only.",
      sourceBoundary: "Track aggregate public metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Facebook aggregates.",
    },
    {
      id: "account-syncsafety-x",
      projectId: "syncsafety",
      name: "SyncSafety X",
      kind: "project",
      platform: "X",
      handle: "@SyncSafety",
      profileUrl: "https://x.com/SyncSafety",
      role: "Project account",
      notes: ["Mock registry row; no X API is connected"],
      accountType: "Project account",
      publicHandle: "@SyncSafety",
      status: "active",
      statusTone: "good",
      purpose: "Manual short-form safety workflow updates.",
      sourceBoundary: "Track aggregate public metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only X aggregate metrics.",
    },
    {
      id: "account-bringhurstdo-website",
      projectId: "bringhurstdo",
      name: "BringhurstDO Website",
      kind: "project",
      platform: "Website",
      handle: "bringhurstdo.com",
      profileUrl: "https://www.bringhurstdo.com",
      role: "Public site",
      notes: ["Public marketing site row; no analytics provider is connected"],
      accountType: "Public site",
      publicHandle: "bringhurstdo.com",
      status: "active",
      statusTone: "good",
      purpose: "Parent-company public pages and project routing.",
      sourceBoundary: "Track public site status and aggregate clicks only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Website clicks", "Leads", "Revenue"],
      forbiddenData: ["Cookies", "Raw logs", "Contact details"],
      integrationPlaceholder: "Future read-only public marketing aggregates.",
    },
  ],
  socialMetricPlaceholders: [
    {
      id: "placeholder-meta-instagram",
      platform: "Meta/Instagram",
      accountIds: [
        "account-founder-instagram",
        "account-bringhurstdo-instagram",
        "account-syncsoap-instagram",
        "account-syncsafety-instagram",
      ],
      status: "placeholder",
      sourceBoundary:
        "Future read-only aggregate public metrics only; no posting or ad-spend writes.",
      futureMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      notes: ["No Meta API is connected", "No ad budget control is connected"],
    },
    {
      id: "placeholder-meta-facebook",
      platform: "Meta/Facebook",
      accountIds: [
        "account-founder-facebook",
        "account-bringhurstdo-facebook",
        "account-syncsoap-facebook",
        "account-syncsafety-facebook",
      ],
      status: "placeholder",
      sourceBoundary:
        "Future read-only aggregate public metrics only; no posting or ad-spend writes.",
      futureMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      notes: ["No Meta API is connected", "No posting API is connected"],
    },
    {
      id: "placeholder-linkedin",
      platform: "LinkedIn",
      accountIds: [
        "account-founder-linkedin",
        "account-bringhurstdo-linkedin",
        "account-syncsoap-linkedin",
        "account-syncsafety-linkedin",
      ],
      status: "placeholder",
      sourceBoundary:
        "Future read-only aggregate page/profile metrics only; manual publishing remains required.",
      futureMetrics: ["Posts", "Followers", "Leads", "Conversations"],
      forbiddenData: ["Credentials", "Private messages", "Contact details"],
      notes: ["No LinkedIn API is connected", "No posting API is connected"],
    },
    {
      id: "placeholder-x",
      platform: "X",
      accountIds: [
        "account-founder-x",
        "account-bringhurstdo-x",
        "account-syncsoap-x",
        "account-syncsafety-x",
      ],
      status: "placeholder",
      sourceBoundary:
        "Future read-only aggregate public metrics only; manual publishing remains required.",
      futureMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      notes: ["No X API is connected", "No posting API is connected"],
    },
  ],
  sourceUpdates: [],
  publicationTargets: [
    {
      id: "target-founder-linkedin-investors",
      accountId: "account-founder-linkedin",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "Kyle Bringhurst LinkedIn",
      platform: "LinkedIn",
      publicHandle: "kyle-bringhurst",
      audience: "investors",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual founder post target. No private messages, contact details, posting API, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-founder-instagram-general",
      accountId: "account-founder-instagram",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "Kyle Bringhurst Instagram",
      platform: "Instagram",
      publicHandle: "@kyle_bringhurst",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual founder post target. No Meta API, private messages, contact details, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-founder-facebook-general",
      accountId: "account-founder-facebook",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "Kyle Bringhurst Facebook",
      platform: "Facebook",
      publicHandle: "Facebook page",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual Facebook target. No Meta Business integration, OAuth, posting API, autoposting, private messages, contact details, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-founder-x-general",
      accountId: "account-founder-x",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "Kyle Bringhurst X",
      platform: "X",
      publicHandle: "@kyle_bringhurst",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual founder post target. No X API, private messages, contact details, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-linkedin-investors",
      accountId: "account-bringhurstdo-linkedin",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO LinkedIn",
      platform: "LinkedIn",
      publicHandle: "bringhurstdo-llc",
      audience: "investors",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual company page target. No LinkedIn API, lead contact storage, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-instagram-general",
      accountId: "account-bringhurstdo-instagram",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO Instagram",
      platform: "Instagram",
      publicHandle: "@BringhurstDO_LLC",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual company target. No Meta API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-facebook-general",
      accountId: "account-bringhurstdo-facebook",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO Facebook",
      platform: "Facebook",
      publicHandle: "Facebook page",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual Facebook target. No Meta Business integration, OAuth, posting API, autoposting, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-x-general",
      accountId: "account-bringhurstdo-x",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO X",
      platform: "X",
      publicHandle: "@BringhurstDOLLC",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual company target. No X API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsoap-linkedin-clinic-owners",
      accountId: "account-syncsoap-linkedin",
      accountStatus: "active",
      projectId: "syncsoap",
      accountName: "SyncSOAP LinkedIn",
      platform: "LinkedIn",
      publicHandle: "syncsoap",
      audience: "clinic owners",
      defaultDestinationUrl: syncSoapDestination,
      sourceBoundary:
        "Manual public post target. No posting API, audience export, inbox data, or clinical payloads.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsoap-instagram-physicians",
      accountId: "account-syncsoap-instagram",
      accountStatus: "active",
      projectId: "syncsoap",
      accountName: "SyncSOAP Instagram",
      platform: "Instagram",
      publicHandle: "@sync.soap",
      audience: "physicians",
      defaultDestinationUrl: syncSoapDestination,
      sourceBoundary:
        "Manual public post target. No Meta API, audience export, private messages, or clinical payloads.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsoap-facebook-clinic-owners",
      accountId: "account-syncsoap-facebook",
      accountStatus: "active",
      projectId: "syncsoap",
      accountName: "SyncSOAP Facebook",
      platform: "Facebook",
      publicHandle: "Facebook page",
      audience: "clinic owners",
      defaultDestinationUrl: syncSoapDestination,
      sourceBoundary:
        "Manual Facebook target. No Meta Business integration, OAuth, posting API, autoposting, audience export, private messages, or clinical payloads.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsoap-x-physicians",
      accountId: "account-syncsoap-x",
      accountStatus: "active",
      projectId: "syncsoap",
      accountName: "SyncSOAP X",
      platform: "X",
      publicHandle: "@SyncSOAP",
      audience: "physicians",
      defaultDestinationUrl: syncSoapDestination,
      sourceBoundary:
        "Manual public thread target. No posting API, audience export, private messages, or clinical payloads.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsafety-linkedin-general",
      accountId: "account-syncsafety-linkedin",
      accountStatus: "active",
      projectId: "syncsafety",
      accountName: "SyncSafety LinkedIn",
      platform: "LinkedIn",
      publicHandle: "syncsafety",
      audience: "EHS leaders",
      defaultDestinationUrl: syncSafetyDestination,
      sourceBoundary:
        "Manual public post target. No posting API or lead contact storage.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsafety-instagram-general",
      accountId: "account-syncsafety-instagram",
      accountStatus: "active",
      projectId: "syncsafety",
      accountName: "SyncSafety Instagram",
      platform: "Instagram",
      publicHandle: "@sync.safety",
      audience: "EHS leaders",
      defaultDestinationUrl: syncSafetyDestination,
      sourceBoundary:
        "Manual public post target. No Meta API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsafety-facebook-general",
      accountId: "account-syncsafety-facebook",
      accountStatus: "active",
      projectId: "syncsafety",
      accountName: "SyncSafety Facebook",
      platform: "Facebook",
      publicHandle: "Facebook page",
      audience: "EHS leaders",
      defaultDestinationUrl: syncSafetyDestination,
      sourceBoundary:
        "Manual Facebook target. No Meta Business integration, OAuth, posting API, autoposting, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsafety-x-general",
      accountId: "account-syncsafety-x",
      accountStatus: "active",
      projectId: "syncsafety",
      accountName: "SyncSafety X",
      platform: "X",
      publicHandle: "@SyncSafety",
      audience: "EHS leaders",
      defaultDestinationUrl: syncSafetyDestination,
      sourceBoundary:
        "Manual public post target. No X API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-blog-general",
      accountId: "account-bringhurstdo-website",
      accountStatus: "active",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO Website",
      platform: "Blog",
      publicHandle: "bringhurstdo.com",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual blog target. No CMS write integration is connected.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
  ],
  contentPackages: [],
  platformDrafts: [],
  publishedPosts: [],
  performanceSnapshots: [],
  businessOutcomes: [],
  projectHealthSnapshots: [
    {
      id: "health-syncsoap-2026-06-06",
      projectId: "syncsoap",
      name: "SyncSOAP",
      siteStatus: "Mock: reachable",
      siteStatusTone: "neutral",
      deployStatus: "Mock: last deploy stable",
      deployStatusTone: "good",
      monthlyCostEstimate: "Mock: review manually",
      tractionNotes: [
        "Small-clinic pilot framing is the near-term bar",
        "Evidence status should remain summarized outside SyncSOAP",
      ],
      nextAction: "Draft metadata export contract before any live pull",
      capturedAt: "2026-06-06",
    },
    {
      id: "health-syncsafety-2026-06-06",
      projectId: "syncsafety",
      name: "SyncSafety",
      siteStatus: "Mock: public page active",
      siteStatusTone: "good",
      deployStatus: "Mock: no deploy check connected",
      deployStatusTone: "neutral",
      monthlyCostEstimate: "Mock: low",
      tractionNotes: [
        "Content pipeline has first safety workflow post ready",
        "Marketing metrics are intentionally not connected",
      ],
      nextAction: "Create read-only status file when source app is ready",
      capturedAt: "2026-06-06",
    },
    {
      id: "health-bringhurstdo-2026-06-06",
      projectId: "bringhurstdo",
      name: "BringhurstDO",
      siteStatus: "Mock: public pages unchanged",
      siteStatusTone: "good",
      deployStatus: "Mock: local build verified",
      deployStatusTone: "good",
      monthlyCostEstimate: "Mock: Vercel hobby-scale",
      tractionNotes: [
        "Private ops routes are Basic Auth protected",
        "Phase 2 remains local/mock-only",
      ],
      nextAction: "Verify production protection plan before deployment",
      capturedAt: "2026-06-06",
    },
  ],
  weeklyReport: {
    id: "weekly-operator-report-2026-06-01",
    weekStart: "2026-06-01",
    weekEnd: "2026-06-07",
    generatedAt: "2026-06-06T09:00:00-04:00",
    mode: "mock",
    summary:
      "Phase 2 turns the private console into a local working surface for content planning, project health snapshots, UTM helper links, and weekly operator review.",
    sections: [
      {
        title: "Operational health",
        tone: "watch",
        items: [
          "SyncSOAP remains an external HIPAA-sensitive source system.",
          "BringhurstDO should consume only aggregate status once a safe export exists.",
          "Current dashboard values are mock placeholders.",
        ],
      },
      {
        title: "Cost and usage",
        tone: "neutral",
        items: [
          "No AWS, Vercel, or AI usage integrations are connected.",
          "Future reports should store summaries, not raw bills or secrets.",
        ],
      },
      {
        title: "Content pipeline",
        tone: "good",
        items: [
          "Draft queue model supports manual planning and posted tracking.",
          "Posting remains manual until explicit approval and stronger controls exist.",
        ],
      },
    ],
    weeklyWins: [
      "Private ops dashboard shell is protected and build-verified.",
      "Content workspace model now separates ideas, drafts, and UTM links.",
      "Project health snapshots are modeled without live credentials.",
    ],
    risksAndBlockers: [
      "Basic Auth is still temporary and should not protect future mutation features alone.",
      "SyncSOAP integration must start from a metadata-only export contract.",
      "Production deployment should wait for env and protection review.",
    ],
    costNotes: [
      "No paid services were added.",
      "Cost estimates are mock notes until aggregate billing summaries are approved.",
    ],
    marketingOutput: [
      "Five mock draft rows are ready for manual review.",
      "Three UTM helper links are generated for public destinations only.",
      "No social posting API is connected.",
    ],
    nextActions: [
      "Review SyncSOAP metadata export fields.",
      "Approve or archive draft rows manually.",
      "Decide whether future reporting should be JSON, Markdown, or both.",
    ],
  },
};

assertNoForbiddenOpsKeys(opsDashboardData);
