import { assertNoForbiddenOpsKeys } from "@/lib/ops/safety";
import type { OpsDashboardData } from "@/lib/ops/types";
import { buildUtmUrl } from "@/lib/ops/utm";

const syncSoapDestination = "https://www.bringhurstdo.com/syncsoap";
const syncSafetyDestination = "https://www.bringhurstdo.com/syncsafety";
const bringhurstDoDestination = "https://www.bringhurstdo.com";

// Metadata-only mock data for the private BringhurstDO operator console.
// Never add PHI, patient identifiers, encounter IDs, transcripts, secret values,
// cookies, tokens, raw logs, or clinical payloads to this module.
export const opsDashboardData: OpsDashboardData = {
  generatedAt: "2026-06-06T09:00:00-04:00",
  boundaries: [
    "Metadata summaries only",
    "No PHI or clinical payloads",
    "No secret values or raw logs",
    "Manual approval before social posting or spend",
  ],
  projects: [
    {
      id: "syncsoap",
      name: "SyncSOAP",
      role: "HIPAA-sensitive clinical app",
      status: "Mock metadata only",
      statusTone: "watch",
      owner: "BringhurstDO",
      environment: "External app, no live connection",
      lastReviewedAt: "2026-06-06",
      metadataBoundary:
        "Only aggregate health, deployment, invite, cost, and evidence summaries belong here.",
      metrics: [
        {
          label: "Site health",
          value: "Mock: healthy",
          detail: "Future source: metadata-only status endpoint",
          tone: "neutral",
        },
        {
          label: "Compliance evidence",
          value: "Mock: collecting",
          detail: "Future source: evidence status summary, not evidence files",
          tone: "watch",
        },
        {
          label: "User / invite counts",
          value: "Mock: pending",
          detail: "Future source: aggregate counts only",
          tone: "neutral",
        },
      ],
      nextActions: [
        "Define a SyncSOAP metadata export contract",
        "Keep HIPAA app data ownership inside SyncSOAP",
        "Review pilot-readiness evidence summary weekly",
      ],
      integrationTodos: [
        "Read-only SyncSOAP health summary",
        "Aggregate AWS cost subtotal",
        "Aggregate AI usage and cost totals",
      ],
    },
    {
      id: "syncsafety",
      name: "SyncSafety",
      role: "Industrial compliance product",
      status: "Mock metadata only",
      statusTone: "neutral",
      owner: "BringhurstDO",
      environment: "Future project metadata feed",
      lastReviewedAt: "2026-06-06",
      metadataBoundary:
        "Only operational status, marketing status, and aggregate business metrics belong here.",
      metrics: [
        {
          label: "Product status",
          value: "Mock: active",
          detail: "Future source: public app uptime summary",
          tone: "good",
        },
        {
          label: "Content calendar",
          value: "Mock: 4 drafts",
          detail: "Draft queue requires manual approval",
          tone: "watch",
        },
        {
          label: "Marketing metrics",
          value: "Mock: not connected",
          detail: "Future source: read-only marketing aggregate",
          tone: "neutral",
        },
      ],
      nextActions: [
        "Create first read-only project status file",
        "Draft LinkedIn launch-support post",
        "Document public metrics worth tracking",
      ],
      integrationTodos: [
        "Read-only deployment status",
        "Read-only marketing aggregate",
        "Content calendar export",
      ],
    },
    {
      id: "bringhurstdo",
      name: "BringhurstDO",
      role: "Parent company and ops aggregator",
      status: "Phase 2 mock workspace",
      statusTone: "good",
      owner: "BringhurstDO",
      environment: "This app, protected by Basic Auth",
      lastReviewedAt: "2026-06-06",
      metadataBoundary:
        "BringhurstDO aggregates summaries; source apps retain their own sensitive data.",
      metrics: [
        {
          label: "Ops console",
          value: "Mock: protected",
          detail: "Basic Auth middleware is temporary",
          tone: "watch",
        },
        {
          label: "Weekly report",
          value: "Mock: expanded",
          detail: "No AI generation connected",
          tone: "good",
        },
        {
          label: "Content queue",
          value: "Mock: working",
          detail: "Manual tracking only; no posting API",
          tone: "good",
        },
      ],
      nextActions: [
        "Replace Basic Auth before mutation features",
        "Review mock operator report every Friday",
        "Keep future integration contracts metadata-only",
      ],
      integrationTodos: [
        "Read-only deployment status",
        "Scheduled local report generation",
        "Future auth provider or SSO",
      ],
    },
  ],
  contentIdeas: [
    {
      id: "idea-syncsoap-small-clinic-pilot",
      projectId: "syncsoap",
      title: "Small-clinic pilot readiness",
      angle:
        "Position SyncSOAP as a practical documentation workflow for small clinics before larger enterprise claims.",
      audience: "clinic owners",
      channelFit: ["LinkedIn", "Blog", "Email"],
      status: "idea",
      riskLevel: "medium",
      sourceBoundary:
        "Use product positioning and aggregate readiness notes only; no clinical payload examples.",
      notes: [
        "Keep claims measured",
        "Emphasize metadata-only evidence posture",
        "Avoid patient examples",
      ],
      createdAt: "2026-06-06",
    },
    {
      id: "idea-syncsoap-charting-fatigue",
      projectId: "syncsoap",
      title: "Charting fatigue without clinical details",
      angle:
        "Talk about documentation burden at the workflow level, not from specific encounters.",
      audience: "physicians",
      channelFit: ["LinkedIn", "X", "Blog"],
      status: "needs review",
      riskLevel: "high",
      sourceBoundary:
        "Use general workflow language only; no anecdotes from patient care.",
      notes: [
        "Review for overclaiming",
        "Avoid scribe-comparison claims without support",
      ],
      createdAt: "2026-06-06",
    },
    {
      id: "idea-syncsafety-osha-friction",
      projectId: "syncsafety",
      title: "OSHA workflow friction",
      angle:
        "Frame SyncSafety as a calmer way to organize incident documentation work.",
      audience: "general",
      channelFit: ["LinkedIn", "Blog"],
      status: "drafted",
      riskLevel: "low",
      sourceBoundary:
        "Use public product positioning and manual planning notes only.",
      notes: ["Keep claims product-led", "No external metrics connected"],
      createdAt: "2026-06-06",
    },
    {
      id: "idea-bringhurstdo-operator-console",
      projectId: "bringhurstdo",
      title: "Operator console philosophy",
      angle:
        "Explain why BringhurstDO aggregates business metadata while source apps keep sensitive data.",
      audience: "investors",
      channelFit: ["Blog", "LinkedIn", "Email"],
      status: "approved",
      riskLevel: "medium",
      sourceBoundary:
        "Discuss architecture principles without exposing internal security details.",
      notes: [
        "Keep private dashboard screenshots out of public posts",
        "Manual approval before publishing",
      ],
      createdAt: "2026-06-06",
    },
  ],
  draftPosts: [
    {
      id: "draft-syncsoap-beta-positioning",
      ideaId: "idea-syncsoap-small-clinic-pilot",
      projectId: "syncsoap",
      title: "SyncSOAP beta positioning update",
      channel: "LinkedIn",
      audience: "clinic owners",
      status: "idea",
      publishWindow: "Week of 2026-06-09",
      bodyPreview:
        "A practical note on small-clinic documentation drag and why the first SyncSOAP pilots stay deliberately narrow.",
      approvalRequired: true,
      utmCampaignId: "utm-syncsoap-beta-linkedin",
      safetyNotes: [
        "No patient stories",
        "No clinical examples",
        "No performance claims without review",
      ],
    },
    {
      id: "draft-syncsoap-physician-workflow",
      ideaId: "idea-syncsoap-charting-fatigue",
      projectId: "syncsoap",
      title: "Physician workflow note",
      channel: "X",
      audience: "physicians",
      status: "needs review",
      publishWindow: "Unscheduled",
      bodyPreview:
        "A short thread about documentation burden using only general workflow language.",
      approvalRequired: true,
      utmCampaignId: "utm-syncsoap-workflow-x",
      safetyNotes: [
        "Review tone carefully",
        "No encounter-level details",
        "No implied clinical output guarantees",
      ],
    },
    {
      id: "draft-syncsafety-osha-workflow",
      ideaId: "idea-syncsafety-osha-friction",
      projectId: "syncsafety",
      title: "OSHA workflow friction post",
      channel: "LinkedIn",
      audience: "general",
      status: "drafted",
      publishWindow: "Week of 2026-06-16",
      bodyPreview:
        "A product-led post about reducing administrative drag in safety documentation workflows.",
      approvalRequired: true,
      utmCampaignId: "utm-syncsafety-osha-linkedin",
      safetyNotes: [
        "Keep claims product-led",
        "Avoid implying automated filing without approval",
      ],
    },
    {
      id: "draft-bringhurstdo-ops-philosophy",
      ideaId: "idea-bringhurstdo-operator-console",
      projectId: "bringhurstdo",
      title: "Parent-company ops philosophy note",
      channel: "Blog",
      audience: "investors",
      status: "approved",
      publishWindow: "Unscheduled",
      bodyPreview:
        "A public-safe explanation of why BringhurstDO aggregates only metadata from project systems.",
      approvalRequired: true,
      utmCampaignId: "utm-bringhurstdo-ops-blog",
      safetyNotes: [
        "Keep ops-console details private",
        "Do not reveal internal cost or security posture",
      ],
    },
    {
      id: "draft-syncsafety-email-seed",
      ideaId: "idea-syncsafety-osha-friction",
      projectId: "syncsafety",
      title: "Safety manager email seed",
      channel: "Email",
      audience: "general",
      status: "posted",
      publishWindow: "Manual log: 2026-06-05",
      bodyPreview:
        "Manual tracking row for a previously sent positioning email; no sending API is connected.",
      approvalRequired: true,
      postedManuallyAt: "2026-06-05",
      utmCampaignId: "utm-syncsafety-email-seed",
      safetyNotes: [
        "Manual posted tracking only",
        "No recipient list stored in BringhurstDO Ops",
      ],
    },
  ],
  utmCampaignLinks: [
    {
      id: "utm-syncsoap-beta-linkedin",
      projectId: "syncsoap",
      label: "SyncSOAP beta LinkedIn",
      destinationUrl: syncSoapDestination,
      source: "linkedin",
      medium: "organic",
      campaign: "syncsoap_beta",
      content: "small_clinic_pilot",
      generatedUrl: buildUtmUrl({
        destinationUrl: syncSoapDestination,
        source: "linkedin",
        medium: "organic",
        campaign: "syncsoap_beta",
        content: "small_clinic_pilot",
      }),
      status: "ready",
      notes: ["Default public SyncSOAP destination", "Manual posting only"],
    },
    {
      id: "utm-syncsoap-workflow-x",
      projectId: "syncsoap",
      label: "SyncSOAP workflow X thread",
      destinationUrl: syncSoapDestination,
      source: "x",
      medium: "organic",
      campaign: "syncsoap_workflow",
      content: "physician_thread",
      generatedUrl: buildUtmUrl({
        destinationUrl: syncSoapDestination,
        source: "x",
        medium: "organic",
        campaign: "syncsoap_workflow",
        content: "physician_thread",
      }),
      status: "mock",
      notes: ["Review copy before use", "No autoposting"],
    },
    {
      id: "utm-syncsafety-osha-linkedin",
      projectId: "syncsafety",
      label: "SyncSafety OSHA LinkedIn",
      destinationUrl: syncSafetyDestination,
      source: "linkedin",
      medium: "organic",
      campaign: "syncsafety_osha",
      content: "workflow_friction",
      generatedUrl: buildUtmUrl({
        destinationUrl: syncSafetyDestination,
        source: "linkedin",
        medium: "organic",
        campaign: "syncsafety_osha",
        content: "workflow_friction",
      }),
      status: "ready",
      notes: ["Default public SyncSafety destination", "Manual posting only"],
    },
    {
      id: "utm-bringhurstdo-ops-blog",
      projectId: "bringhurstdo",
      label: "BringhurstDO ops philosophy blog",
      destinationUrl: bringhurstDoDestination,
      source: "blog",
      medium: "owned",
      campaign: "bringhurstdo_ops",
      content: "metadata_aggregator_note",
      generatedUrl: buildUtmUrl({
        destinationUrl: bringhurstDoDestination,
        source: "blog",
        medium: "owned",
        campaign: "bringhurstdo_ops",
        content: "metadata_aggregator_note",
      }),
      status: "mock",
      notes: ["Public parent-company destination", "Manual publishing only"],
    },
    {
      id: "utm-syncsafety-email-seed",
      projectId: "syncsafety",
      label: "SyncSafety manual email seed",
      destinationUrl: syncSafetyDestination,
      source: "email",
      medium: "manual",
      campaign: "syncsafety_seed",
      content: "safety_manager_note",
      generatedUrl: buildUtmUrl({
        destinationUrl: syncSafetyDestination,
        source: "email",
        medium: "manual",
        campaign: "syncsafety_seed",
        content: "safety_manager_note",
      }),
      status: "ready",
      notes: ["Manual send tracking only", "No recipient list stored here"],
    },
  ],
  weeklyScorecard: [
    {
      id: "posts",
      label: "Posts",
      value: "5",
      unit: "manual rows",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "good",
      notes: ["Counts draft rows marked posted or ready for manual publishing"],
    },
    {
      id: "followers",
      label: "Followers",
      value: "Manual",
      unit: "weekly total",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "neutral",
      notes: ["Enter aggregate follower totals only"],
    },
    {
      id: "websiteClicks",
      label: "Website Clicks",
      value: "Mock: 14",
      unit: "UTM clicks",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "watch",
      notes: ["Use public page click totals only; no visitor identifiers"],
    },
    {
      id: "leads",
      label: "Leads",
      value: "Manual",
      unit: "aggregate count",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "neutral",
      notes: ["Counts only; no names, emails, or contact details"],
    },
    {
      id: "conversations",
      label: "Conversations",
      value: "Manual",
      unit: "aggregate count",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "neutral",
      notes: ["Track count and source category, not message content"],
    },
    {
      id: "spend",
      label: "Spend",
      value: "$0",
      unit: "manual weekly total",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "good",
      notes: ["No ad-spend mutation is connected"],
    },
    {
      id: "revenue",
      label: "Revenue",
      value: "$0",
      unit: "manual weekly total",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      tone: "neutral",
      notes: ["Use aggregate totals only"],
    },
  ],
  manualMetricEntries: [
    {
      id: "metric-posts-2026-06-07",
      projectId: "bringhurstdo",
      metricId: "posts",
      label: "Manual posts prepared",
      value: "5",
      unit: "rows",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      enteredAt: "2026-06-06",
      notes: ["Includes approved, ready, and manually posted draft rows"],
    },
    {
      id: "metric-clicks-2026-06-07",
      projectId: "bringhurstdo",
      metricId: "websiteClicks",
      label: "UTM link clicks",
      value: "14",
      unit: "aggregate clicks",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      enteredAt: "2026-06-06",
      notes: ["Placeholder manual total; no analytics provider connected"],
    },
    {
      id: "metric-spend-2026-06-07",
      projectId: "bringhurstdo",
      metricId: "spend",
      label: "Paid spend",
      value: "0",
      unit: "USD",
      weekStart: "2026-06-01",
      weekEnd: "2026-06-07",
      source: "manual",
      enteredAt: "2026-06-06",
      notes: ["No ad platform mutation or budget control connected"],
    },
  ],
  accountRegistry: [
    {
      id: "account-founder-linkedin",
      projectId: "kyle-bringhurst",
      name: "Kyle Bringhurst LinkedIn",
      kind: "founder",
      platform: "LinkedIn",
      handle: "kyle-bringhurst",
      profileUrl: "https://www.linkedin.com/in/kyle-bringhurst/",
      role: "Founder account",
      notes: ["User-provided registry row; verify public profile URL before posting"],
      accountType: "Founder profile",
      publicHandle: "kyle-bringhurst",
      status: "manual-only",
      statusTone: "watch",
      purpose: "Manual founder-led updates after approval.",
      sourceBoundary:
        "Track public profile context and aggregate metrics only; do not store inbox content.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Conversations", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Contact details"],
      integrationPlaceholder: "Future read-only LinkedIn aggregate metrics.",
    },
    {
      id: "account-founder-instagram",
      projectId: "kyle-bringhurst",
      name: "Kyle Bringhurst Instagram",
      kind: "founder",
      platform: "Instagram",
      handle: "@kyle_bringhurst",
      profileUrl: "https://www.instagram.com/kyle_bringhurst",
      role: "Founder account",
      notes: ["Mock registry row; manual posting only"],
      accountType: "Founder profile",
      publicHandle: "@kyle_bringhurst",
      status: "planned",
      statusTone: "neutral",
      purpose: "Optional founder visual updates after approval.",
      sourceBoundary:
        "Track public profile context and aggregate metrics only; no private message content.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Instagram aggregates.",
    },
    {
      id: "account-founder-facebook",
      projectId: "kyle-bringhurst",
      name: "Kyle Bringhurst Facebook",
      kind: "founder",
      platform: "Facebook",
      handle: "kylebringhurst",
      profileUrl: "https://www.facebook.com/kylebringhurst",
      role: "Founder account",
      notes: ["Mock registry row; no page mutation is connected"],
      accountType: "Founder profile",
      publicHandle: "kylebringhurst",
      status: "planned",
      statusTone: "neutral",
      purpose: "Optional founder updates after approval.",
      sourceBoundary:
        "Track public profile context and aggregate metrics only; no private message content.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Facebook aggregates.",
    },
    {
      id: "account-founder-x",
      projectId: "kyle-bringhurst",
      name: "Kyle Bringhurst X",
      kind: "founder",
      platform: "X",
      handle: "@kyle_bringhurst",
      profileUrl: "https://x.com/kyle_bringhurst",
      role: "Founder account",
      notes: ["Mock registry row; manual short-form posting only"],
      accountType: "Founder profile",
      publicHandle: "@kyle_bringhurst",
      status: "planned",
      statusTone: "neutral",
      purpose: "Manual short-form updates and UTM-linked threads.",
      sourceBoundary: "Track public aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only X aggregate metrics.",
    },
    {
      id: "account-bringhurstdo-linkedin",
      projectId: "bringhurstdo",
      name: "BringhurstDO LinkedIn",
      kind: "project",
      platform: "LinkedIn",
      handle: "bringhurstdo-llc",
      profileUrl: "https://www.linkedin.com/company/bringhurstdo-llc/",
      role: "Parent company account",
      notes: ["Mock registry row; public company positioning only"],
      accountType: "Company page",
      publicHandle: "bringhurstdo-llc",
      status: "planned",
      statusTone: "neutral",
      purpose: "Parent-company updates and project routing.",
      sourceBoundary: "Track public page context and aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Leads", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Contact details"],
      integrationPlaceholder: "Future read-only LinkedIn aggregate metrics.",
    },
    {
      id: "account-bringhurstdo-instagram",
      projectId: "bringhurstdo",
      name: "BringhurstDO Instagram",
      kind: "project",
      platform: "Instagram",
      handle: "@BringhurstDO_LLC",
      profileUrl: "https://www.instagram.com/BringhurstDO_LLC",
      role: "Parent company account",
      notes: ["Mock registry row; no Meta API is connected"],
      accountType: "Project account",
      publicHandle: "@BringhurstDO_LLC",
      status: "planned",
      statusTone: "neutral",
      purpose: "Optional public visual updates after approval.",
      sourceBoundary: "Track public aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Instagram aggregates.",
    },
    {
      id: "account-bringhurstdo-facebook",
      projectId: "bringhurstdo",
      name: "BringhurstDO Facebook",
      kind: "project",
      platform: "Facebook",
      handle: "bringhurstdo",
      profileUrl: "https://www.facebook.com/bringhurstdo",
      role: "Parent company account",
      notes: ["Mock registry row; no Meta API is connected"],
      accountType: "Project page",
      publicHandle: "bringhurstdo",
      status: "planned",
      statusTone: "neutral",
      purpose: "Optional public company updates after approval.",
      sourceBoundary: "Track public aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Facebook aggregates.",
    },
    {
      id: "account-bringhurstdo-x",
      projectId: "bringhurstdo",
      name: "BringhurstDO X",
      kind: "project",
      platform: "X",
      handle: "@BringhurstDOLLC",
      profileUrl: "https://x.com/BringhurstDOLLC",
      role: "Parent company account",
      notes: ["Mock registry row; no X API is connected"],
      accountType: "Project account",
      publicHandle: "@BringhurstDOLLC",
      status: "planned",
      statusTone: "neutral",
      purpose: "Manual short-form company updates.",
      sourceBoundary: "Track public aggregate metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only X aggregate metrics.",
    },
    {
      id: "account-syncsoap-linkedin",
      projectId: "syncsoap",
      name: "SyncSOAP LinkedIn",
      kind: "project",
      platform: "LinkedIn",
      handle: "syncsoap",
      profileUrl: "https://www.linkedin.com/showcase/syncsoap/",
      role: "Project account",
      notes: ["Mock registry row; SyncSOAP content remains metadata-only"],
      accountType: "Project company page",
      publicHandle: "syncsoap",
      status: "planned",
      statusTone: "watch",
      purpose: "Manual product positioning and pilot-readiness posts.",
      sourceBoundary:
        "Track account presence and aggregate public metrics only; no clinical payloads.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Contact lists"],
      integrationPlaceholder: "Future read-only LinkedIn aggregate metrics.",
    },
    {
      id: "account-syncsoap-instagram",
      projectId: "syncsoap",
      name: "SyncSOAP Instagram",
      kind: "project",
      platform: "Instagram",
      handle: "@sync.soap",
      profileUrl: "https://www.instagram.com/sync.soap",
      role: "Project account",
      notes: ["Mock registry row; no patient stories or clinical examples"],
      accountType: "Project account",
      publicHandle: "@sync.soap",
      status: "planned",
      statusTone: "neutral",
      purpose: "Optional visual workflow-positioning posts.",
      sourceBoundary:
        "Track aggregate public metrics only; SyncSOAP remains metadata-only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Instagram aggregates.",
    },
    {
      id: "account-syncsoap-facebook",
      projectId: "syncsoap",
      name: "SyncSOAP Facebook",
      kind: "project",
      platform: "Facebook",
      handle: "syncsoap",
      profileUrl: "https://www.facebook.com/syncsoap",
      role: "Project account",
      notes: ["Mock registry row; public business metadata only"],
      accountType: "Project page",
      publicHandle: "syncsoap",
      status: "planned",
      statusTone: "neutral",
      purpose: "Optional project updates after approval.",
      sourceBoundary:
        "Track aggregate public metrics only; no clinical payloads or message bodies.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Facebook aggregates.",
    },
    {
      id: "account-syncsoap-x",
      projectId: "syncsoap",
      name: "SyncSOAP X",
      kind: "project",
      platform: "X",
      handle: "@SyncSOAP",
      profileUrl: "https://x.com/SyncSOAP",
      role: "Project account",
      notes: ["Mock registry row; approved UTM links only"],
      accountType: "Project account",
      publicHandle: "@SyncSOAP",
      status: "planned",
      statusTone: "neutral",
      purpose: "Short workflow-positioning posts with approved UTM links.",
      sourceBoundary:
        "Track public aggregate counts only; no private message content.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only X aggregate metrics.",
    },
    {
      id: "account-syncsafety-linkedin",
      projectId: "syncsafety",
      name: "SyncSafety LinkedIn",
      kind: "project",
      platform: "LinkedIn",
      handle: "syncsafety",
      profileUrl: "https://www.linkedin.com/showcase/syncsafety/",
      role: "Project account",
      notes: ["Mock registry row; manual safety-workflow posts only"],
      accountType: "Project company page",
      publicHandle: "syncsafety",
      status: "manual-only",
      statusTone: "good",
      purpose: "Manual safety-workflow posts and launch notes.",
      sourceBoundary: "Track aggregate public metrics and UTM totals only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Leads", "Website clicks"],
      forbiddenData: ["Credentials", "Lead contact details", "Message bodies"],
      integrationPlaceholder: "Future read-only LinkedIn aggregate metrics.",
    },
    {
      id: "account-syncsafety-instagram",
      projectId: "syncsafety",
      name: "SyncSafety Instagram",
      kind: "project",
      platform: "Instagram",
      handle: "@sync.safety",
      profileUrl: "https://www.instagram.com/sync.safety",
      role: "Project account",
      notes: ["Mock registry row; no Meta API is connected"],
      accountType: "Project account",
      publicHandle: "@sync.safety",
      status: "planned",
      statusTone: "neutral",
      purpose: "Optional visual education channel for safety workflow topics.",
      sourceBoundary: "Track aggregate public metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Instagram aggregates.",
    },
    {
      id: "account-syncsafety-facebook",
      projectId: "syncsafety",
      name: "SyncSafety Facebook",
      kind: "project",
      platform: "Facebook",
      handle: "syncsafety",
      profileUrl: "https://www.facebook.com/syncsafety",
      role: "Project account",
      notes: ["Mock registry row; manual publishing only"],
      accountType: "Project page",
      publicHandle: "syncsafety",
      status: "planned",
      statusTone: "neutral",
      purpose: "Optional safety-workflow updates after approval.",
      sourceBoundary: "Track aggregate public metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only Meta/Facebook aggregates.",
    },
    {
      id: "account-syncsafety-x",
      projectId: "syncsafety",
      name: "SyncSafety X",
      kind: "project",
      platform: "X",
      handle: "@SyncSafety",
      profileUrl: "https://x.com/SyncSafety",
      role: "Project account",
      notes: ["Mock registry row; no X API is connected"],
      accountType: "Project account",
      publicHandle: "@SyncSafety",
      status: "planned",
      statusTone: "neutral",
      purpose: "Manual short-form safety workflow updates.",
      sourceBoundary: "Track aggregate public metrics only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      integrationPlaceholder: "Future read-only X aggregate metrics.",
    },
    {
      id: "account-bringhurstdo-website",
      projectId: "bringhurstdo",
      name: "BringhurstDO Website",
      kind: "project",
      platform: "Website",
      handle: "bringhurstdo.com",
      profileUrl: "https://www.bringhurstdo.com",
      role: "Public site",
      notes: ["Public marketing site row; no analytics provider is connected"],
      accountType: "Public site",
      publicHandle: "bringhurstdo.com",
      status: "active",
      statusTone: "good",
      purpose: "Parent-company public pages and project routing.",
      sourceBoundary: "Track public site status and aggregate clicks only.",
      manualReviewCadence: "Weekly",
      allowedMetrics: ["Website clicks", "Leads", "Revenue"],
      forbiddenData: ["Cookies", "Raw logs", "Contact details"],
      integrationPlaceholder: "Future read-only public marketing aggregates.",
    },
  ],
  socialMetricPlaceholders: [
    {
      id: "placeholder-meta-instagram",
      platform: "Meta/Instagram",
      accountIds: [
        "account-founder-instagram",
        "account-bringhurstdo-instagram",
        "account-syncsoap-instagram",
        "account-syncsafety-instagram",
      ],
      status: "placeholder",
      sourceBoundary:
        "Future read-only aggregate public metrics only; no posting or ad-spend writes.",
      futureMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      notes: ["No Meta API is connected", "No ad budget control is connected"],
    },
    {
      id: "placeholder-meta-facebook",
      platform: "Meta/Facebook",
      accountIds: [
        "account-founder-facebook",
        "account-bringhurstdo-facebook",
        "account-syncsoap-facebook",
        "account-syncsafety-facebook",
      ],
      status: "placeholder",
      sourceBoundary:
        "Future read-only aggregate public metrics only; no posting or ad-spend writes.",
      futureMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      notes: ["No Meta API is connected", "No posting API is connected"],
    },
    {
      id: "placeholder-linkedin",
      platform: "LinkedIn",
      accountIds: [
        "account-founder-linkedin",
        "account-bringhurstdo-linkedin",
        "account-syncsoap-linkedin",
        "account-syncsafety-linkedin",
      ],
      status: "placeholder",
      sourceBoundary:
        "Future read-only aggregate page/profile metrics only; manual publishing remains required.",
      futureMetrics: ["Posts", "Followers", "Leads", "Conversations"],
      forbiddenData: ["Credentials", "Private messages", "Contact details"],
      notes: ["No LinkedIn API is connected", "No posting API is connected"],
    },
    {
      id: "placeholder-x",
      platform: "X",
      accountIds: [
        "account-founder-x",
        "account-bringhurstdo-x",
        "account-syncsoap-x",
        "account-syncsafety-x",
      ],
      status: "placeholder",
      sourceBoundary:
        "Future read-only aggregate public metrics only; manual publishing remains required.",
      futureMetrics: ["Posts", "Followers", "Website clicks"],
      forbiddenData: ["Credentials", "Private messages", "Audience exports"],
      notes: ["No X API is connected", "No posting API is connected"],
    },
  ],
  sourceUpdates: [
    {
      id: "source-update-syncsoap-beta-2026-06-06",
      projectId: "syncsoap",
      title: "SyncSOAP pilot positioning update",
      updateType: "product-update",
      summary:
        "Manual update: keep near-term SyncSOAP positioning focused on small-clinic pilot readiness and metadata-only evidence posture.",
      sourceDate: "2026-06-06",
      sourceBoundary:
        "Product/business update only. No clinical payloads, patient stories, transcripts, or encounter details.",
      approvalRequired: true,
      createdAt: "2026-06-06T10:00:00-04:00",
      notes: [
        "Use public-safe language",
        "Manual approval before any post",
        "No AI generation connected",
      ],
    },
  ],
  publicationTargets: [
    {
      id: "target-founder-linkedin-investors",
      accountId: "account-founder-linkedin",
      projectId: "bringhurstdo",
      accountName: "Kyle Bringhurst LinkedIn",
      platform: "LinkedIn",
      publicHandle: "kyle-bringhurst",
      audience: "investors",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual founder post target. No private messages, contact details, posting API, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-founder-instagram-general",
      accountId: "account-founder-instagram",
      projectId: "bringhurstdo",
      accountName: "Kyle Bringhurst Instagram",
      platform: "Instagram",
      publicHandle: "@kyle_bringhurst",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual founder post target. No Meta API, private messages, contact details, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-founder-facebook-general",
      accountId: "account-founder-facebook",
      projectId: "bringhurstdo",
      accountName: "Kyle Bringhurst Facebook",
      platform: "Facebook",
      publicHandle: "kylebringhurst",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual founder post target. No Meta API, private messages, contact details, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-founder-x-general",
      accountId: "account-founder-x",
      projectId: "bringhurstdo",
      accountName: "Kyle Bringhurst X",
      platform: "X",
      publicHandle: "@kyle_bringhurst",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual founder post target. No X API, private messages, contact details, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-linkedin-investors",
      accountId: "account-bringhurstdo-linkedin",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO LinkedIn",
      platform: "LinkedIn",
      publicHandle: "bringhurstdo-llc",
      audience: "investors",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual company page target. No LinkedIn API, lead contact storage, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-instagram-general",
      accountId: "account-bringhurstdo-instagram",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO Instagram",
      platform: "Instagram",
      publicHandle: "@BringhurstDO_LLC",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual company target. No Meta API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-facebook-general",
      accountId: "account-bringhurstdo-facebook",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO Facebook",
      platform: "Facebook",
      publicHandle: "bringhurstdo",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual company target. No Meta API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-x-general",
      accountId: "account-bringhurstdo-x",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO X",
      platform: "X",
      publicHandle: "@BringhurstDOLLC",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual company target. No X API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsoap-linkedin-clinic-owners",
      accountId: "account-syncsoap-linkedin",
      projectId: "syncsoap",
      accountName: "SyncSOAP LinkedIn",
      platform: "LinkedIn",
      publicHandle: "syncsoap",
      audience: "clinic owners",
      defaultDestinationUrl: syncSoapDestination,
      sourceBoundary:
        "Manual public post target. No posting API, audience export, inbox data, or clinical payloads.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsoap-instagram-physicians",
      accountId: "account-syncsoap-instagram",
      projectId: "syncsoap",
      accountName: "SyncSOAP Instagram",
      platform: "Instagram",
      publicHandle: "@sync.soap",
      audience: "physicians",
      defaultDestinationUrl: syncSoapDestination,
      sourceBoundary:
        "Manual public post target. No Meta API, audience export, private messages, or clinical payloads.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsoap-facebook-clinic-owners",
      accountId: "account-syncsoap-facebook",
      projectId: "syncsoap",
      accountName: "SyncSOAP Facebook",
      platform: "Facebook",
      publicHandle: "syncsoap",
      audience: "clinic owners",
      defaultDestinationUrl: syncSoapDestination,
      sourceBoundary:
        "Manual public post target. No Meta API, audience export, private messages, or clinical payloads.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsoap-x-physicians",
      accountId: "account-syncsoap-x",
      projectId: "syncsoap",
      accountName: "SyncSOAP X",
      platform: "X",
      publicHandle: "@SyncSOAP",
      audience: "physicians",
      defaultDestinationUrl: syncSoapDestination,
      sourceBoundary:
        "Manual public thread target. No posting API, audience export, private messages, or clinical payloads.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsafety-linkedin-general",
      accountId: "account-syncsafety-linkedin",
      projectId: "syncsafety",
      accountName: "SyncSafety LinkedIn",
      platform: "LinkedIn",
      publicHandle: "syncsafety",
      audience: "general",
      defaultDestinationUrl: syncSafetyDestination,
      sourceBoundary:
        "Manual public post target. No posting API or lead contact storage.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsafety-instagram-general",
      accountId: "account-syncsafety-instagram",
      projectId: "syncsafety",
      accountName: "SyncSafety Instagram",
      platform: "Instagram",
      publicHandle: "@sync.safety",
      audience: "general",
      defaultDestinationUrl: syncSafetyDestination,
      sourceBoundary:
        "Manual public post target. No Meta API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsafety-facebook-general",
      accountId: "account-syncsafety-facebook",
      projectId: "syncsafety",
      accountName: "SyncSafety Facebook",
      platform: "Facebook",
      publicHandle: "syncsafety",
      audience: "general",
      defaultDestinationUrl: syncSafetyDestination,
      sourceBoundary:
        "Manual public post target. No Meta API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-syncsafety-x-general",
      accountId: "account-syncsafety-x",
      projectId: "syncsafety",
      accountName: "SyncSafety X",
      platform: "X",
      publicHandle: "@SyncSafety",
      audience: "general",
      defaultDestinationUrl: syncSafetyDestination,
      sourceBoundary:
        "Manual public post target. No X API, private messages, or audience export.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
    {
      id: "target-bringhurstdo-blog-general",
      accountId: "account-bringhurstdo-website",
      projectId: "bringhurstdo",
      accountName: "BringhurstDO Website",
      platform: "Blog",
      publicHandle: "bringhurstdo.com",
      audience: "general",
      defaultDestinationUrl: bringhurstDoDestination,
      sourceBoundary:
        "Manual blog target. No CMS write integration is connected.",
      approvalRequired: true,
      postingMode: "manual-only",
      spendMode: "manual-approval-required",
    },
  ],
  contentPackages: [
    {
      id: "package-syncsoap-beta-positioning",
      sourceUpdateId: "source-update-syncsoap-beta-2026-06-06",
      title: "SyncSOAP beta positioning package",
      projectIds: ["syncsoap"],
      publicationTargetIds: [
        "target-syncsoap-linkedin-clinic-owners",
        "target-syncsoap-x-physicians",
      ],
      status: "needs review",
      approvalRequired: true,
      createdAt: "2026-06-06T10:10:00-04:00",
      updatedAt: "2026-06-06T10:20:00-04:00",
      notes: [
        "Local/mock content package",
        "Manual approval before posting",
        "Every draft slot carries a UTM link",
      ],
    },
  ],
  platformDrafts: [
    {
      id: "platform-draft-syncsoap-beta-linkedin",
      contentPackageId: "package-syncsoap-beta-positioning",
      sourceUpdateId: "source-update-syncsoap-beta-2026-06-06",
      publicationTargetId: "target-syncsoap-linkedin-clinic-owners",
      projectId: "syncsoap",
      platform: "LinkedIn",
      accountName: "SyncSOAP LinkedIn",
      title: "Small-clinic pilot readiness",
      body:
        "Manual draft slot: SyncSOAP is staying focused on a narrow small-clinic pilot path before making larger workflow claims.",
      status: "needs review",
      approvalRequired: true,
      utmCampaignId: "utm-package-syncsoap-beta-linkedin",
      generatedUrl: buildUtmUrl({
        destinationUrl: syncSoapDestination,
        source: "linkedin",
        medium: "organic",
        campaign: "package_syncsoap_beta",
        content: "clinic_owner_slot",
      }),
      safetyNotes: [
        "No patient stories",
        "No clinical payloads",
        "Manual approval before posting",
      ],
      updatedAt: "2026-06-06T10:20:00-04:00",
    },
    {
      id: "platform-draft-syncsoap-beta-x",
      contentPackageId: "package-syncsoap-beta-positioning",
      sourceUpdateId: "source-update-syncsoap-beta-2026-06-06",
      publicationTargetId: "target-syncsoap-x-physicians",
      projectId: "syncsoap",
      platform: "X",
      accountName: "SyncSOAP X",
      title: "Documentation workflow focus",
      body:
        "Manual draft slot: Keep the SyncSOAP beta conversation at the workflow and pilot-readiness level.",
      status: "slot",
      approvalRequired: true,
      utmCampaignId: "utm-package-syncsoap-beta-x",
      generatedUrl: buildUtmUrl({
        destinationUrl: syncSoapDestination,
        source: "x",
        medium: "organic",
        campaign: "package_syncsoap_beta",
        content: "physician_slot",
      }),
      safetyNotes: [
        "No encounter details",
        "No performance claims without review",
        "Manual approval before posting",
      ],
      updatedAt: "2026-06-06T10:20:00-04:00",
    },
  ],
  publishedPosts: [
    {
      id: "published-post-syncsoap-beta-linkedin",
      platformDraftId: "platform-draft-syncsoap-beta-linkedin",
      publicationTargetId: "target-syncsoap-linkedin-clinic-owners",
      status: "not posted",
      manualNotes: [
        "URL is added only after manual posting",
        "No posting API is connected",
      ],
    },
  ],
  performanceSnapshots: [
    {
      id: "performance-syncsoap-beta-linkedin-2026-06-06",
      publishedPostId: "published-post-syncsoap-beta-linkedin",
      capturedAt: "2026-06-06",
      source: "manual",
      impressions: "0",
      clicks: "0",
      reactions: "0",
      comments: "0",
      saves: "0",
      notes: ["Manual placeholder until post URL exists"],
    },
  ],
  businessOutcomes: [
    {
      id: "outcome-syncsoap-beta-package-2026-06-06",
      contentPackageId: "package-syncsoap-beta-positioning",
      capturedAt: "2026-06-06",
      source: "manual",
      leads: "0",
      conversations: "0",
      revenue: "$0",
      notes: ["Aggregate outcomes only; no contact details stored"],
    },
  ],
  projectHealthSnapshots: [
    {
      id: "health-syncsoap-2026-06-06",
      projectId: "syncsoap",
      name: "SyncSOAP",
      siteStatus: "Mock: reachable",
      siteStatusTone: "neutral",
      deployStatus: "Mock: last deploy stable",
      deployStatusTone: "good",
      monthlyCostEstimate: "Mock: review manually",
      tractionNotes: [
        "Small-clinic pilot framing is the near-term bar",
        "Evidence status should remain summarized outside SyncSOAP",
      ],
      nextAction: "Draft metadata export contract before any live pull",
      capturedAt: "2026-06-06",
    },
    {
      id: "health-syncsafety-2026-06-06",
      projectId: "syncsafety",
      name: "SyncSafety",
      siteStatus: "Mock: public page active",
      siteStatusTone: "good",
      deployStatus: "Mock: no deploy check connected",
      deployStatusTone: "neutral",
      monthlyCostEstimate: "Mock: low",
      tractionNotes: [
        "Content pipeline has first safety workflow post ready",
        "Marketing metrics are intentionally not connected",
      ],
      nextAction: "Create read-only status file when source app is ready",
      capturedAt: "2026-06-06",
    },
    {
      id: "health-bringhurstdo-2026-06-06",
      projectId: "bringhurstdo",
      name: "BringhurstDO",
      siteStatus: "Mock: public pages unchanged",
      siteStatusTone: "good",
      deployStatus: "Mock: local build verified",
      deployStatusTone: "good",
      monthlyCostEstimate: "Mock: Vercel hobby-scale",
      tractionNotes: [
        "Private ops routes are Basic Auth protected",
        "Phase 2 remains local/mock-only",
      ],
      nextAction: "Verify production protection plan before deployment",
      capturedAt: "2026-06-06",
    },
  ],
  weeklyReport: {
    id: "weekly-operator-report-2026-06-01",
    weekStart: "2026-06-01",
    weekEnd: "2026-06-07",
    generatedAt: "2026-06-06T09:00:00-04:00",
    mode: "mock",
    summary:
      "Phase 2 turns the private console into a local working surface for content planning, project health snapshots, UTM helper links, and weekly operator review.",
    sections: [
      {
        title: "Operational health",
        tone: "watch",
        items: [
          "SyncSOAP remains an external HIPAA-sensitive source system.",
          "BringhurstDO should consume only aggregate status once a safe export exists.",
          "Current dashboard values are mock placeholders.",
        ],
      },
      {
        title: "Cost and usage",
        tone: "neutral",
        items: [
          "No AWS, Vercel, or AI usage integrations are connected.",
          "Future reports should store summaries, not raw bills or secrets.",
        ],
      },
      {
        title: "Content pipeline",
        tone: "good",
        items: [
          "Draft queue model supports manual planning and posted tracking.",
          "Posting remains manual until explicit approval and stronger controls exist.",
        ],
      },
    ],
    weeklyWins: [
      "Private ops dashboard shell is protected and build-verified.",
      "Content workspace model now separates ideas, drafts, and UTM links.",
      "Project health snapshots are modeled without live credentials.",
    ],
    risksAndBlockers: [
      "Basic Auth is still temporary and should not protect future mutation features alone.",
      "SyncSOAP integration must start from a metadata-only export contract.",
      "Production deployment should wait for env and protection review.",
    ],
    costNotes: [
      "No paid services were added.",
      "Cost estimates are mock notes until aggregate billing summaries are approved.",
    ],
    marketingOutput: [
      "Five mock draft rows are ready for manual review.",
      "Three UTM helper links are generated for public destinations only.",
      "No social posting API is connected.",
    ],
    nextActions: [
      "Review SyncSOAP metadata export fields.",
      "Approve or archive draft rows manually.",
      "Decide whether future reporting should be JSON, Markdown, or both.",
    ],
  },
};

assertNoForbiddenOpsKeys(opsDashboardData);
